### ISSUE TITLE
have a issue

### ISSUE THREAD

**Issue by Kanson4** [jardiamj/homeassistant#2]
In HA, I used it as a switch, and the send switch command MCP23017 did not have any action. After checking it for two days (I am a PY newbie), I don't know what't wrong,but it worked by modify the following parts：

    def turn_on(self, **kwargs):

        """Turn the device on."""
        self._pin.value = False # not self._invert_logic  <-------this
        self._state = True
        self.schedule_update_ha_state()

    def turn_off(self, **kwargs):
        """Turn the device off."""
        self._pin.value = True #True and not self._invert_logic  <--------this
        self._state = False
        self.schedule_update_ha_state()

**Comment by jardiamj** [comment]
Hi @Kanson4,

There was a logic error in my code, I substituted ```self._pin.value = True and not self._invert_logic``` with ```self._pin.value = self._invert_logic```, that should fix the issue.
Can you try this current version and let me know if it works? At the moment, I don't have physical access to my pi to test it.

**Comment by Kanson4** [comment]
hi
Yeah,it worked.but i found another issue.
HA configure: invert_logic: True ,when HA start,all MCP23017 relay is on.but Entity switch.status is off in HA.

**Comment by Kanson4** [comment]
I tryed to configure invert_logic to false , it seems that everything is fine, but in HA, the on/off cmd is reversed.

**Comment by jardiamj** [comment]
That is what invert_logic is supposed to do, invert the logic of low/high with the on/off states. What do you mean by the on/off cmd is reversed in HA?

The idea of invert logic is that you can use it with let's say relays that are active on low (they switch on when a ground signal is provided). Or for example, if you inverse connect an led where the positive side is connected to vdd and the negative side is connected to a pin on the MCP23017 then it will turn on when that pin goes low and off when the pin goes high.

**Comment by Kanson4** [comment]
The reason I tried to change invert_logic was because the LED was turned on when I sent the switch.turn_off command. When the switch.turn_on command is sent, the LED is turned off.
When I set the invert_logic setting to not true, the switch CMD is correct.

**Comment by jardiamj** [comment]
So, if I understand well, it is now working as expected when ```invert_logic: False```. Is that correct?

**Comment by Kanson4** [comment]
According to my circuit, invert_logic should not be set to 1, just test

**Comment by Kanson4** [comment]
Sorry I typed wrongly
#When I set the invert_logic setting to not true, the switch CMD is correct.
When I set the invert_logic setting to true, the switch CMD is correct.

**Comment by jardiamj** [comment]
I'm sorry, I don't think I understand. ```invert_logic``` is set to False by default, you only need to use ```invert_logic: True``` if you need something to turn on when the pin goes low and off when it goes high.
I don't have physical access to my pi at the moment, but I'll test it when I get home.

**Comment by Kanson4** [comment]
I understand the role of invert_logic, my circuit set invert_logic to false is correct. Maybe I can't make it clear. I probably mean that I sent the service switch.turn_off at HA, and the corresponding LED is turned on, which means that the on/off service is reversed.

**Comment by Kanson4** [comment]
I modified the following parts to be perfect. My level is low, the simple question is too complicated, I am sorry.

    def turn_on(self, **kwargs):
        """Turn the device on."""
        self._pin.value = self._invert_logic #<----------THIS
        self._state = True
        self.schedule_update_ha_state()

    def turn_off(self, **kwargs):
        """Turn the device off."""
        self._pin.value = not self._invert_logic   #<----------THIS
        self._state = False
        self.schedule_update_ha_state()
